spring.application.name=backend

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/aepdb?replicaSet=rs0}
spring.data.mongodb.auto-index-creation=true

server.servlet.context-path=/api
server.port=8080

app.jwt.secret=${JWT_SECRET:YWVwLXN5c3RlbS1kZW51bmNpYXMtMjAyNi1qd3Qtc2VjdXJlLXRva2Vu}
app.jwt.expiration-ms=86400000

logging.level.com.aep=INFO
